version: 2
formats: []
sphinx:
  # Path to your Sphinx configuration file.
  configuration: source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
    install:
        - requirements: source/requirements.txt
        - method: pip
          path: .
